### ISSUE TITLE
connect: no such file or directory

### ISSUE THREAD

**Issue by godfuture** [deep-compute/docker-file-log-driver#7]
When trying to install I get the error message:
`Error response from daemon: dial unix /run/docker/plugins/00c3c00674b3e458e89f71a366fbdbcfe23955014970782c00f5c353cc30e97b/log.sock: connect: no such file or directory`

I am using openmediavault and moved my docker home (normally /var/lib/docker) to another location. Is it possible to adopt this plugin such that other homes are possible?

**Comment by supriyopaul** [comment]
> 00c3c00674b3e458e89f71a366fbdbcfe23955014970782c00f5c353cc30e97b

@godfuture we did not test this plugin on any other dist other than Ubuntu. Can you try installing any other plugin and see if the installation  succeeds? It will help debug this problem.

**Comment by jaswanth098** [comment]
@godfuture I have changed docker home location using the following [link](https://linuxconfig.org/how-to-move-docker-s-default-var-lib-docker-to-another-directory-on-ubuntu-debian-linux) and tried to install plugin this worked fine for me.
Could you let us know if you have followed any other way to change your docker home location?
also, let us know which distribution you are using?

**Comment by godfuture** [comment]
I guess [Openmediavault 4](https://www.openmediavault.org/) uses Debian 9. I think OMV is shifting the home location the same way.

I will try to install another plugin and report here.

**Comment by schklom** [comment]
> @godfuture I have changed docker home location using the following [link](https://linuxconfig.org/how-to-move-docker-s-default-var-lib-docker-to-another-directory-on-ubuntu-debian-linux) and tried to install plugin this worked fine for me.

Any chance you know how to adapt this for Rootless Docker?
For example, my `docker.service` in systemd doesn't have
```
ExecStart=/usr/bin/dockerd -H fd://
```
but instead
```
ExecStart=/home/schklom/bin/dockerd-rootless.sh
```
